### ISSUE TITLE
Flutter integrations

### ISSUE THREAD

**Issue by KipCrossing** [RightToAskOrg/key-storage-expts#1]
Looks like flutter supports xamarin forms if we were ever going to collab on an app and need this.

https://flutter.dev/docs/get-started/flutter-for/xamarin-forms-devs

There's also a basic enclave package for flutter https://pub.dev/packages/key_enclave

**Comment by KipCrossing** [comment]
Feel free to close this issue. I just wanted to start a discussion. (We should take advantage of GitHub discussions, actually)

**Comment by vteague** [comment]
Hi Kip,

Terrific - thanks. - I was wondering about that.  It may be less relevant to key storage but very relevant to collaboration on all the important work of parsing and interpreting legislation, committees, hansard, etc.  It'd be great to work together on that.

Discussions are a great idea - best to use the one in righttoask-docs so that everything is in the same place:
https://github.com/RightToAskOrg/righttoask-docs/discussions/
